version: "3.9"
services:
  cs2-watchdog:
    build: ./watchdog
    image: cs2-watchdog:latest
    restart: unless-stopped
    environment:
      - STEAM_USERNAME=
      - STEAM_PASSWORD=
    volumes:
      - ./repo:/repo
      - ./hooks/watchdog:/hooks
      
  cs2-server:
    build: ./server
    image: cs2-server:latest
    restart: unless-stopped
    environment:
      - SERVER_NAME=
      - MAP=de_inferno
      - SERVER_PW=  # Set your desired server password here
      - RCON_PW=  # Set your desired RCON password here
      - PORT=27015  # Set your desired server port here
      - GAME_TYPE=0  # Set your desired game type here
      - GAME_MODE=1  # Set your desired game mode here
      - MAX_PLAYERS=10  # Set your desired maximum player count here
    volumes:
      - ./repo:/repo
      - ./hooks/server:/hooks
    network_mode: host
